spring:
  datasource:
    username: root
    password: kcw92163
    url: jdbc:mysql://localhost:3306/vulsystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

#关闭thymeleaf的缓存
#spring:
  thymeleaf:
    cache: false
#
  messages:
    basename: i18n.login
#  mvc:
    date-format: yyyy-MM-dd


---
mybatis:
  type-aliases-package: com.mxnet.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
